[package]
name = "piping-server"
version = "0.8.1"
authors = ["Ryo Ota <nwtgck@nwtgck.org>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["stream", "server", "client", "http1", "h2"] }
futures = "0.3"
structopt = "0.3"
http = "0.2"
# FIXME: Not use "full"
tokio = { version = "1.0", features = ["full"] }
rustls = "0.19"
hyper-rustls = "0.22"
futures-util = "0.3"
tokio-rustls = "0.22"
log = "0.4"
env_logger = "0.8"
pin-project-lite = "0.2"

[dev-dependencies]
specit = {version  = "0.3.0", features = ["tokio"] }
