[package]
name = "piping-server"
version = "0.8.5"
authors = ["Ryo Ota <nwtgck@nwtgck.org>"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["stream", "server", "http1", "http2"] }
futures = { version = "0.3", default-features = false, features = ["std"] }
structopt = "0.3"
http = "0.2"
tokio = { version = "1.12", features = ["rt-multi-thread", "macros"] }
rustls = "0.20"
rustls-pemfile = "0.2"
hyper-rustls = "0.22"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
tokio-rustls = { git = "https://github.com/tokio-rs/tls.git", rev = "8501aafae5c5d0ec97a4cdca25d9e96b63f1d02d" }
log = "0.4"
env_logger = "0.9"
pin-project-lite = "0.2"

[dev-dependencies]
specit = {version  = "0.4.0", features = ["tokio"] }
