[package]
name = "piping-server"
version = "0.4.9"
authors = ["Ryo Ota <nwtgck@gmail.com>"]
edition = "2018"

[dependencies]
hyper = { version = "0.13", features = ["stream"] }
futures = "0.3"
structopt = "0.3"
http = "0.2"
